version: '3'
networks:
  default:
    external:
      name: bl-network # create with docker network create bl-network

services:
  solr:
    container_name: ${SOLR_HOST}
    #restart: always
    image: solr:8
    environment:
      SOLR_JAVA_MEM: "-Xms512m -Xmx512m"
    ports:
      - "8985:8983"
    volumes:
      - /docker/solr/data:/var/solr/data
      - /docker/solr/configsets:/opt/solr/server/solr/configsets
    entrypoint:
      - bash
      - "-c"
      - "precreate-core ${SOLR_CORE_SEARCHBLOCKS} /opt/solr/server/solr/configsets/${SOLR_CORE_SEARCHBLOCKS};
         exec solr -f"

  searchblocks-app:
    container_name: searchblocks-app
    #restart: always
    build:
      context: .
    depends_on:
      - searchblocks-db
      - solr
    environment:
      DB_USER: ${DB_USER_SEARCHBLOCKS}
      DB_PW: ${DB_PW_SEARCHBLOCKS}
      DB_HOST: ${DB_HOST_SEARCHBLOCKS}
      DB_NAME: ${DB_NAME_SEARCHBLOCKS}
      RAILS_ENV: development
      SITE_NAME: 127.0.0.1
      SECRET_KEY_BASE: ${SECRET_KEY_BASE_SEARCHBLOCKS}
      SOLR_URL: http://${SOLR_HOST}:8983/solr/${SOLR_CORE_SEARCHBLOCKS}
      #puma workers and threads
      WEB_CONCURRENCY: 1
      RAILS_MAX_THREADS: 5
    command: sh -c "bin/rails server -e development -b 0.0.0.0"
    volumes:
      - .:/usr/src/app
      - /docker/searchblocks/log:/usr/src/app/log
    ports:
      - "3013:3000"

  searchblocks-db:
    container_name: ${DB_HOST_SEARCHBLOCKS}
    image: postgres:14
    #restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PW_SEARCHBLOCKS}
      POSTGRES_USER: ${DB_USER_SEARCHBLOCKS}
      POSTGRES_DB: ${DB_NAME_SEARCHBLOCKS}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /docker/searchblocks/db:/var/lib/postgresql/data